courses=AWS-&-DEVOPS,FULL-STACK-JAVA-DEVELOPMENT
AWS-&-DEVOPS=Windows-Server,Network,Linux,Python,SQL
FULL-STACK-JAVA-DEVELOPMENT=BackEnd,FrontEnd
BackEnd=SQL,Hibernate,MongoDB,Java,SQL
FrontEnd=CSS,Bootstrap,HTML


Hibernate=1-Hibernate-Intro,2-Hibernate-Annotations
1-Hibernate-Intro=https://www.googleapis.com/drive/v3/files/1_II2eMskApO7N9QCyYjROVMvofVHiJT4?alt=media&key=AIzaSyAMi67pMAVX4eccRfzKJs01r4OnDtSGtVQ
2-Hibernate-Annotations=https://www.googleapis.com/drive/v3/files/1j8Q3f_jmU_MWQArjsHnXmCTVDodg7vJO?alt=media&key=AIzaSyAMi67pMAVX4eccRfzKJs01r4OnDtSGtVQ



drivebase=https://www.googleapis.com/drive/v3/files/[fileId]?alt=media&key=[apiKey]


jsonIdOnDrive=1hMEyKfdsX_fR8be87vikZeULFsNM2RYu
apiKey=AIzaSyAMi67pMAVX4eccRfzKJs01r4OnDtSGtVQ